### ISSUE TITLE
Why isn't this a bundler plugin?

### ISSUE THREAD

**Issue by pboling** [segiddins/bundler-compose#3]
Ref: https://bundler.io/guides/bundler_plugins.html

It seems that the core aspect of being a bundler plugin is having a `plugins.rb` at the root, and that is missing in this repo.

Mostly this is curiosity, as I am considering building a bundler plugin.

**Comment by segiddins** [comment]
Because this gem doesn't need to be. By having an executable file named `bundler-compose`, it is invokable via `bundle compose`.

**Comment by pboling** [comment]
Thanks for the explanation!  I appreciate it!
